# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='uploaded_file1',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='news',
            name='uploaded_file2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='uploaded_file3',
        ),
    ]
